apiVersion: v1
kind: Service
metadata:
  name: calculator-service
  labels:
    app: calculator
    app.kubernetes.io/component: backend
spec:
  selector:
    app: calculator
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
  type: ClusterIP
